version: '3.4'

services:
  bolna-xtts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-8000}:8000"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
